DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS dataset;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE dataset
(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  owner_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_used TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  uri TEXT NOT NULL,
  FOREIGN KEY (owner_id) REFERENCES user (id)
);
